// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://crpywkqmidrhaoxxeqcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNycHl3a3FtaWRyaGFveHhlcWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDk1NjIsImV4cCI6MjA3MDEyNTU2Mn0.iizAL45zwyVOKXCDMzrzBhzFxVItvqeyEamxiUxHoes";

// Example usage:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage, // Session will persist via localStorage in browser
      persistSession: true, // Keeps session alive across page refreshes
      autoRefreshToken: true, // Renews token before expiry automatically
    },
  }
);
